language: php

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: 5

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install --no-interaction --no-progress --prefer-dist

script:
  - vendor/bin/phpunit
