language: php

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: 5

sudo: false

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

before_install:
  - composer self-update -vvv --no-interaction

install:
  - composer install -vvv --no-interaction --no-progress --prefer-dist

script:
  - vendor/bin/phpunit
